/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import glbank.Account;
import glbank.Transaction;
import glbank.database.ConnectionProvider;
import java.sql.SQLException;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Client
 */
public class PanelAccounts extends javax.swing.JPanel  {

    private int idc;
    int index;
    private List<Account> list;
    Transaction trans;
    private int idemp;

    /**
     * Creates new form Acounts
     */
    public PanelAccounts(int idc, int idemp) throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        this.idc = idc;
        this.idemp=idemp;
        initComponents();
        initAcountList();
        lblBalanceAmount.setText("");
        jLabel4.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblBalanceAmount = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Account id:");

        jLabel2.setText("Balance:");

        lblBalanceAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblBalanceAmount.setText("BalanceAmount");

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("0");

        jButton1.setText("Add +");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sub -");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cash transaction:");

        jButton3.setText("Add new account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblBalanceAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel3)))
                                .addGap(129, 129, 129))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblBalanceAmount)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        index = jComboBox1.getSelectedIndex();

        if (index > 0) {
            try {
                lblBalanceAmount.setText(new ConnectionProvider().getBalance(list.get(index - 1).getIdacc()) + " EUR");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            lblBalanceAmount.setText("");
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          
        try {
            ConnectionProvider connection = new ConnectionProvider();
            Account account = new Account(generateAcc(), idc, 0);
            if (!connection.existsAccount(account)) {
                connection.addNewAccount(account);
                initAcountList();
              /*  AddAccountBox aab = new AddAccountBox((JFrame) this.getRootPane().getParent(),true);
                 aab.setLocationRelativeTo(null);
                 aab.setVisible(true);*/
              JOptionPane.showMessageDialog(null, "Account '"+String.valueOf(account.getIdacc())+"/2701"+"' was successfully created!" , "Creating account " , JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private long generateAcc() {
        String generatedIdacc = "";
        long idacc;
        do {
            for (int i = 0; i < 10; i++) {
                Random ran = new Random();
                int x = ran.nextInt(9) + 1;
                generatedIdacc += x;
            }
            idacc = Long.parseLong(generatedIdacc);
        } while (idacc % 11 == 0);
        return idacc;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            if (index > 0) {
                float number = Float.parseFloat(jTextField1.getText());
                    if(number>0.1){
                (list.get(index - 1)).setBalance((list.get(index - 1).getBalance()) + number);
                jTextField1.setText("0");
                new ConnectionProvider().updateCashTransactions(list.get(index - 1), idemp, '+', number);

                lblBalanceAmount.setText("" + list.get(index - 1).getBalance() + " EUR");
                JOptionPane.showMessageDialog(null, number+" EUR was added to "+list.get(index - 1).getIdacc()+"/2701" , "" , JOptionPane.INFORMATION_MESSAGE);
            }else
                        JOptionPane.showMessageDialog(null, " must by greater than 0.10 EUR" , "" , JOptionPane.INFORMATION_MESSAGE);
                    }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            System.out.println("Error: " + ex.toString());
            jTextField1.setText("0");
            JOptionPane.showMessageDialog(null, "Input is not number!" , "" , JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            if (index > 0) {
                float number = Float.parseFloat(jTextField2.getText());
                    if(number>0.1){
                        if(new ConnectionProvider().getBalance((list.get(index - 1).getIdacc()))>=number){
                (list.get(index - 1)).setBalance((list.get(index - 1).getBalance()) - number);
                jTextField2.setText("0");
                new ConnectionProvider().updateCashTransactions(list.get(index - 1), idemp, '-', number);
                
                lblBalanceAmount.setText("" + list.get(index - 1).getBalance() + " EUR");
                JOptionPane.showMessageDialog(null, number+"EUR was deducted from "+list.get(index - 1).getIdacc()+"/2701" , "" , JOptionPane.INFORMATION_MESSAGE);
                        }else{JOptionPane.showMessageDialog(null, " Lack of money in the account!" , "" , JOptionPane.INFORMATION_MESSAGE);}
                    }else
                        JOptionPane.showMessageDialog(null, " must by greater than 0.10 EUR" , "" , JOptionPane.INFORMATION_MESSAGE);
                        
                        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PanelAccounts.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            System.out.println("Error: " + ex.toString());
            jTextField2.setText("0");
            JOptionPane.showMessageDialog(null, "Input is not number!" , "" , JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblBalanceAmount;
    // End of variables declaration//GEN-END:variables

    private void initAcountList() throws ClassNotFoundException, InstantiationException, IllegalAccessException, SQLException {
        list = new ConnectionProvider().getAccounts(idc);
        if (list == null) {
            return;
        } else {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Choose:");
            if (list != null && list.size() > 0) {
                for (Account account : list) {
                    String item = "" + account.getIdacc();
                    jComboBox1.addItem(item + " / 2701");
                }
            }
        }
    }
    
   
}
