/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.panels;

import javax.swing.JLabel;

/**
 *
 * @author Client
 */
public class HistoryOfTransactions extends javax.swing.JPanel {

    /**
     * Creates new form HistoryOfTransactions
     */
    public HistoryOfTransactions() {
        initComponents();
        
         JLabel[] desc ={lblDesc1,lblDesc2,lblDesc3,lblDesc4,lblDesc5,lblDesc6,lblDesc7,lblDesc8,lblDesc9,lblDesc10};
    JLabel[] amount ={lblAmount1,lblAmount2,lblAmount3,lblAmount4,lblAmount5,lblAmount6,lblAmount7,lblAmount8,lblAmount9,lblAmount10};
    JLabel[] date ={lblDate1,lblDate2,lblDate3,lblDate4,lblDate5,lblDate6,lblDate7,lblDate8,lblDate9,lblDate10};
        
        clearHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblDate2 = new javax.swing.JLabel();
        lblDate3 = new javax.swing.JLabel();
        lblDate4 = new javax.swing.JLabel();
        lblDate5 = new javax.swing.JLabel();
        lblDate6 = new javax.swing.JLabel();
        lblDate7 = new javax.swing.JLabel();
        lblDate8 = new javax.swing.JLabel();
        lblDate9 = new javax.swing.JLabel();
        lblDate10 = new javax.swing.JLabel();
        lblDesc1 = new javax.swing.JLabel();
        lblDesc2 = new javax.swing.JLabel();
        lblDesc3 = new javax.swing.JLabel();
        lblDesc4 = new javax.swing.JLabel();
        lblDesc5 = new javax.swing.JLabel();
        lblDesc6 = new javax.swing.JLabel();
        lblDesc7 = new javax.swing.JLabel();
        lblDesc8 = new javax.swing.JLabel();
        lblDesc9 = new javax.swing.JLabel();
        lblDesc10 = new javax.swing.JLabel();
        lblAmount1 = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        lblAmount3 = new javax.swing.JLabel();
        lblAmount4 = new javax.swing.JLabel();
        lblAmount5 = new javax.swing.JLabel();
        lblAmount6 = new javax.swing.JLabel();
        lblAmount7 = new javax.swing.JLabel();
        lblAmount8 = new javax.swing.JLabel();
        lblAmount9 = new javax.swing.JLabel();
        lblAmount10 = new javax.swing.JLabel();

        jButton1.setText(">");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Date and time");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Description");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Amount");

        lblDate1.setText("jLabel4");

        lblDate2.setText("jLabel5");

        lblDate3.setText("jLabel6");

        lblDate4.setText("jLabel7");

        lblDate5.setText("jLabel8");

        lblDate6.setText("jLabel9");

        lblDate7.setText("jLabel10");

        lblDate8.setText("jLabel11");

        lblDate9.setText("jLabel12");

        lblDate10.setText("jLabel13");

        lblDesc1.setText("jLabel14");

        lblDesc2.setText("jLabel15");

        lblDesc3.setText("jLabel16");

        lblDesc4.setText("jLabel17");

        lblDesc5.setText("jLabel18");

        lblDesc6.setText("jLabel19");

        lblDesc7.setText("jLabel20");

        lblDesc8.setText("jLabel21");

        lblDesc9.setText("jLabel22");

        lblDesc10.setText("jLabel23");

        lblAmount1.setText("jLabel24");

        lblAmount2.setText("jLabel25");

        lblAmount3.setText("jLabel26");

        lblAmount4.setText("jLabel27");

        lblAmount5.setText("jLabel28");

        lblAmount6.setText("jLabel29");

        lblAmount7.setText("jLabel30");

        lblAmount8.setText("jLabel31");

        lblAmount9.setText("jLabel32");

        lblAmount10.setText("jLabel33");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDate10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(lblDesc10)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDate2)
                            .addComponent(lblDate3)
                            .addComponent(lblDate4)
                            .addComponent(lblDate5)
                            .addComponent(lblDate6)
                            .addComponent(lblDate7)
                            .addComponent(lblDate8)
                            .addComponent(lblDate9))
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDesc3)
                            .addComponent(lblDesc2)
                            .addComponent(lblDesc4)
                            .addComponent(lblDesc5)
                            .addComponent(lblDesc6)
                            .addComponent(lblDesc7)
                            .addComponent(lblDesc8)
                            .addComponent(lblDesc9))
                        .addGap(338, 338, 338)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount2)
                            .addComponent(lblAmount3)
                            .addComponent(lblAmount4)
                            .addComponent(lblAmount5)
                            .addComponent(lblAmount6)
                            .addComponent(lblAmount7)
                            .addComponent(lblAmount8)
                            .addComponent(lblAmount9)
                            .addComponent(lblAmount10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblDate1))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDesc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(338, 338, 338)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblAmount1))
                        .addGap(79, 79, 79)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDate1)
                        .addComponent(lblAmount1))
                    .addComponent(lblDesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate2)
                    .addComponent(lblDesc2)
                    .addComponent(lblAmount2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate3)
                    .addComponent(lblDesc3)
                    .addComponent(lblAmount3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate4)
                    .addComponent(lblDesc4)
                    .addComponent(lblAmount4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate5)
                    .addComponent(lblDesc5)
                    .addComponent(lblAmount5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate6)
                    .addComponent(lblDesc6)
                    .addComponent(lblAmount6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate7)
                    .addComponent(lblDesc7)
                    .addComponent(lblAmount7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate8)
                    .addComponent(lblDesc8)
                    .addComponent(lblAmount8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate9)
                    .addComponent(lblDesc9)
                    .addComponent(lblAmount9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate10)
                            .addComponent(lblDesc10)
                            .addComponent(lblAmount10))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAmount1;
    private javax.swing.JLabel lblAmount10;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblAmount3;
    private javax.swing.JLabel lblAmount4;
    private javax.swing.JLabel lblAmount5;
    private javax.swing.JLabel lblAmount6;
    private javax.swing.JLabel lblAmount7;
    private javax.swing.JLabel lblAmount8;
    private javax.swing.JLabel lblAmount9;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDate10;
    private javax.swing.JLabel lblDate2;
    private javax.swing.JLabel lblDate3;
    private javax.swing.JLabel lblDate4;
    private javax.swing.JLabel lblDate5;
    private javax.swing.JLabel lblDate6;
    private javax.swing.JLabel lblDate7;
    private javax.swing.JLabel lblDate8;
    private javax.swing.JLabel lblDate9;
    private javax.swing.JLabel lblDesc1;
    private javax.swing.JLabel lblDesc10;
    private javax.swing.JLabel lblDesc2;
    private javax.swing.JLabel lblDesc3;
    private javax.swing.JLabel lblDesc4;
    private javax.swing.JLabel lblDesc5;
    private javax.swing.JLabel lblDesc6;
    private javax.swing.JLabel lblDesc7;
    private javax.swing.JLabel lblDesc8;
    private javax.swing.JLabel lblDesc9;
    // End of variables declaration//GEN-END:variables

    private void clearHistory() {
     
   
     for(int i =0;i<10;i++){
         
     }
    }
}
